### ISSUE TITLE
🐛 [BUG] `Logs` unrecorded full error

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#101]
## 🐛 Bug description [Please make everyone to understand it]

When I get a "file not found" error, compare the IDE and `logs`; 
the logs are missing some info: 

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/476521a4-e4b8-43ac-a1ea-2bacf0ee0fc1)

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/94fe9ae4-d83c-445c-8be7-4d952bfd61e3)

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.1

- **Platform**: MacOS M1Max

**Comment by SAKURA-CAT** [comment]
We use the traceback library for error tracing, which differs from console printing. Generally, the traceback library provides more detailed tracing, but it doesn't imply that we haven't fully recorded the error.
