### ISSUE TITLE
[BUG] When charts show float numbers, they sometimes display wrong

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#105]
## 🐛 Bug description [Please make everyone to understand it]

<img width="922" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/20cfb548-4849-40bf-96f1-ae632d0cdae9">

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.1

- **Platform**: MacOS M1Max

**Comment by xiaolin199912** [comment]
Take a look at this, and optimize the rules for `large numbers` and `small numbers` (scientific notation).

**Comment by SAKURA-CAT** [comment]
fixed by #196
