### ISSUE TITLE
有关server部分优化的提议

### ISSUE THREAD

**Issue by swpfY** [SwanHubX/SwanLab#114]
1. 引入SQLite数据库和ORM。由于涉及到项目信息的“增删查改”，将基础配置信息写入数据库然后操作会更方便一些，操作JSON文件比较麻烦而且没有关系映射。ORM库例如：[Peewee](https://github.com/coleifer/peewee)、[SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy)、[Prisma](https://github.com/RobertCraigie/prisma-client-py)（python版本不成熟，不推荐使用）
2. 将路由集中，将 Handler 分散。目前是将路由和 Handler 部分写在一起的，由于Handler部分的代码过多，会对排查造成影响。

**Comment by xiaolin199912** [comment]
New perspective🤔

**Comment by SAKURA-CAT** [comment]
1与 #5 有所重复，并且我们确实正在思考相关优化，感谢提议！

**Comment by swpfY** [comment]
> 1 与 #5 有所重复，并且我们确实正在思考相关优化，感谢提议！

第1点的提议主要是基本配置信息，将日志写入文件是没问题的

**Comment by SAKURA-CAT** [comment]
至于 2 ，事实上在server.modules中存在相关解耦尝试，不过目前处于敏捷开发阶段，相关优化未来会提上日程

**Comment by SAKURA-CAT** [comment]
> > 1 与 #5 有所重复，并且我们确实正在思考相关优化，感谢提议！
> 
> 
> 
> 第1点的提议主要是基本配置信息，将日志写入文件是没问题的

明白，在项目设计阶段我们主要考虑了tag的信息存储，其他部分确实没有过多考虑.

**Comment by SAKURA-CAT** [comment]
closed by #236
