### ISSUE TITLE
[FEATURE] More elegant modified project/experimental information

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#116]
## 🤩 Features description [Please make everyone to understand it]

- [x] Experiment name check: word count, format
- [x] Experimental information check: word count
- [x] Optimization for tips
- [x] Back-end verification

## 👍 What problem does this feature solve

More elegant modified project/experimental information

**Comment by xiaolin199912** [comment]
格式部分参考Github仓库：
- 项目名/实验名不能超过100个字符
- 描述名不能超过255个字符
- 项目名只能包含字母、中文、数字、连字符（_和-），不能以连字符开头或结尾
- 实验名只能包含字母、数字、连字符（_和-），不能以连字符开头或结尾
- 描述名可以包含任何字符，前后空格自动去除。
