### ISSUE TITLE
🐛 [BUG] Logs Display Error

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#124]
## 🐛 Bug description [Please make everyone to understand it]

Test Code：
```python
import swanlab

# Initialize
swanlab.init()

for epoch in range(1, 20):
    print("epoch", epoch)
    # Tracking index: `epoch`
    swanlab.log({"epoch": epoch})
```

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/ac295fe9-f969-47f1-be76-b8b74cc36c6f)

## 🚑 Any additional [like screenshots]

- **SwanLab Version**:v0.1.2

- **Platform**:MacOS M1Max

**Comment by Feudalman** [comment]
I really need the corresponding log file to locate the bug. Can you upload it ？

**Comment by Feudalman** [comment]
OK I reproduce the bug through the example code successfully, there is no more need for the log file.
