### ISSUE TITLE
[BUG] feature/delete 问题汇总

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#146]
## 🐛 Bug description [Please make everyone to understand it]

- [x]  #145 
- [x] 保留六位数字
- [ ] 终止实验的状态
- [x] #147
- [x] Git仓库没有时，显示`None`
- [x] 实验进行中，还可以编辑
- [x] 修改进行中「编辑」和「删除」的UI（Disable，有Tip）

**Comment by Feudalman** [comment]
@SAKURA-CAT 我这主机名没啥问题，你看看这个问题在 mac 上的表现 0.o

**Comment by Feudalman** [comment]
第四条到第七条已经在 #140 分支完成修复

**Comment by xiaolin199912** [comment]
主机名问题无需修改： #145
