### ISSUE TITLE
 [FEATURE] More elegant document website

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#153]
## 🤩 Features description [Please make everyone to understand it]

A document website maintained by ourselves

## 👍 What problem does this feature solve

Document display and some information release

## 👾 What does the proposed API look like

We can refer to the documentation website of [Vue3](https://cn.vuejs.org/guide/quick-start.html).

## 🚑 Any additional [like screenshots]

<img width="1440" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/79990647/04d2431c-a4dc-4100-bf33-b6d1bcfd08e8">

**Comment by xiaolin199912** [comment]
we will release Docs website in v0.3.0
