### ISSUE TITLE
更好的浮点数保留逻辑

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#155]
## 🤩 Features description [Please make everyone to understand it]

保留逻辑：以小数点后最后一个连续的0开始保留4位
例子：
- `8.123456789`保留为`8.1234`
- `0.012345678`保留为`0.01234`
- `0.000123456`保留为`0.0001234`

**Comment by Feudalman** [comment]
Now, we use a function in `/vue/utils/common.js` to format target data.

And there are some rules:
![image](https://github.com/SwanHubX/SwanLab/assets/74649535/de00d0a5-3ea9-4e55-9f5c-e83f5c6e46c4)

We only format data using our own function in web js.

**Comment by Feudalman** [comment]
There are some tests in `/vue/test`:
![image](https://github.com/SwanHubX/SwanLab/assets/74649535/de6505e7-0cbc-406e-aae2-025fa07ce020)
