### ISSUE TITLE
Suggest adding support for automatic registration of argparse parameters in config

### ISSUE THREAD

**Issue by defineHong** [SwanHubX/SwanLab#16]
It is recommended to support automatic registration of `argparse` parameters in the `swanlab.init` function's config.

**Comment by xiaolin199912** [comment]
`Argparase` parameter registration method case：
![img_v3_026g_a8d9d611-5332-4324-b0be-caf4e39da5ag](https://github.com/SwanHubX/SwanLab/assets/58305964/793eb680-66d5-4a07-98ca-b9d68eb42f32)
