### ISSUE TITLE
[BUG] "print" should not exist in the source code.

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#163]
## 🐛 Bug description [Please make everyone to understand it]

In the source code, the "print" function should not exist, as it prevents users from controlling whether or not it prints.

## 👾 Expected result

use `swanlog` to print info

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.3

- **Platform**: macos

<img width="254" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/79990647/7daa1962-24eb-4d03-a7da-3a5f943631f2">

**Comment by xiaolin199912** [comment]
#169
