### ISSUE TITLE
[QUESTION] 发布版本时将包文件放在Release中

### ISSUE THREAD

**Issue by swpfY** [SwanHubX/SwanLab#174]
发布版本时可以将 python 的 `whl` 包和前端编译后的文件打一个压缩包放在 Release 中，方便直接下载。

**Comment by Feudalman** [comment]
找了下，没看到能快速使用的 action
可以先本地打包，在 release 界面里面选择上传

**Comment by xiaolin199912** [comment]
[pypi](https://pypi.org/project/swanlab/#files)上有2个包，1个whl和1个tar.gz，是不是指的tar.gz？

**Comment by swpfY** [comment]
> [pypi](https://pypi.org/project/swanlab/#files)上有2个包，1个whl和1个tar.gz，是不是指的tar.gz？

whl就可以了，前端也可以把编译后的打一个包

**Comment by swpfY** [comment]
> 找了下，没看到能快速使用的 action 可以先本地打包，在 release 界面里面选择上传

可参考：
- https://github.com/SwanHubX/req-preprocess/blob/main/.github/workflows/release.yml
- https://github.com/softprops/action-gh-release
