### ISSUE TITLE
[FEATURE] UI adjustment

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#209]
## 🤩 Features description [Please make everyone to understand it]

- [x] Header UI
- [x] Tab SVG
- [x] Project Dashboard UI
- [x] State add SVG
- [x] 重构表格样式
- [x] 首页布局重构
- [x] 重构sidebar
- [x] 重构表格交互

**Comment by xiaolin199912** [comment]
Project Dashboard also has a UI ajustmant, UI at Figma "Export CSV"
