### ISSUE TITLE
[FEATURE] Refactor Default Experiment Name format

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#219]
## 🤩 Features description [Please make everyone to understand it]

默认实验名称改为：
1. 如果有设置experiment_name：{experiment_name} _ {Month(缩写)}{Day}_{Hour}-{Minute}-{Second}_{Hostname}，例子：resnet50_Jan17_11-23-33_MacBook-Pro.local
2. 如果没有设置experiment_name：{Month(缩写)}{Day}_{Hour}-{Minute}-{Second}_{Hostname}，例子：Jan17_11-23-33_MacBook-Pro.local

**Comment by SAKURA-CAT** [comment]
下版本再说

**Comment by xiaolin199912** [comment]
swanlab.init增加1个参数'experiment_name_suffix'：
1. 默认值就是1楼那个后缀，支持关闭后缀（False）或用户替换为自己的后缀
2. 实验名重复无所谓（现在的目录结构应该支持这种）

**Comment by SAKURA-CAT** [comment]
> swanlab.init增加1个参数'experiment_name_suffix'：
> 
> 1. 默认值就是1楼那个后缀，支持关闭后缀（False）或用户替换为自己的后缀
> 2. 实验名重复无所谓（现在的目录结构应该支持这种）

此外，目前init已经存在了suffix参数

**Comment by xiaolin199912** [comment]
优化swanlab.ini->suffix参数的功能：
1. 如果为"default"，则使用默认后缀
2. 如果为None，则不用后缀
3. 如果是其他，则将其作为后缀
