### ISSUE TITLE
[BUG] When swanlab.log value type is incorrect, Summary and GridView don't display

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#227]
## 🐛 Bug description [Please make everyone to understand it]

When swanlab.log value type is incorrect, such as string, Summary and GridView don't display:
<img width="2073" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/39261c75-79ca-47d7-8708-76054aff082c">

<img width="1948" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/659e0976-96e8-4d45-a4de-4bf281ff28f1">

## 🧑‍💻 Step to reproduce

test code:

```python
import swanlab

swanlab.init()

swanlab.log(
    {
        'loss': "nan",
        "acc":0.7
    }
)
```

## 👾 Expected result

- Summary and GridView can display
- Summary and GridView can show string type

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.4

**Comment by xiaolin199912** [comment]
In machine learning training, the value can sometimes be 'nan', which is of string type.

**Comment by SAKURA-CAT** [comment]
> In machine learning training, the value can sometimes be 'nan', which is of string type.

所以期望的显示方式是？

**Comment by SAKURA-CAT** [comment]
@Feudalman Your problem，please fix it

**Comment by defineHong** [comment]
对于NAN值我认为直接算成0就可以了 @SAKURA-CAT

**Comment by xiaolin199912** [comment]
> 对于NAN值我认为直接算成0就可以了 @SAKURA-CAT

这也许需要更多的思考，如何在保留原有线条的情况下，更好地显示你的训练NAN了——比如nan值换算为0，但是Chart组件内新增一个组件显示当前的value，value为nan时会标红等。

😄 Need more think

**Comment by SAKURA-CAT** [comment]
所以目前应该怎么处理

**Comment by xiaolin199912** [comment]
> 所以目前应该怎么处理



> > > In machine learning training, the value can sometimes be 'nan', which is of string type.
> > 
> > 
> > 所以期望的显示方式是？
> 
> 先和字符串的处理方式一致，Charts为Eror状态，Summary和GridView显示值为nan

用这个

**Comment by SAKURA-CAT** [comment]
> > 所以目前应该怎么处理
> 
> > > > In machine learning training, the value can sometimes be 'nan', which is of string type.
> > > 
> > > 
> > > 所以期望的显示方式是？
> > 
> > 
> > 先和字符串的处理方式一致，Charts为Eror状态，Summary和GridView显示值为nan
> 
> 用这个

如果是和字符串的处理方式一致，summary和gridView将不显示这个字段

**Comment by xiaolin199912** [comment]
1. 如果log类型不匹配
summary和gridview显示，但是显示的是“TypeError”, 后面有文档网站了，再在旁边加个跳转链接——让用户无死角地知道自己哪里用出问题了

2. 如果nan：
图表NaN的部分断开，hover显示NaN
summary和gridview显示，显示为'NaN'

**Comment by SAKURA-CAT** [comment]
> 1. 如果log类型不匹配: summary和gridview显示，但是显示的是“TypeError”, 后面有文档网站了，再在旁边加个跳转链接——让用户无死角地知道自己哪里用出问题了
> 
> 
> 
> 2. 如果nan：图表NaN的部分断开，hover显示NaN，summary和gridview显示，显示为'NaN'

我们将在v0.2.0解决此问题

**Comment by xiaolin199912** [comment]
> > 1. 如果log类型不匹配: summary和gridview显示，但是显示的是“TypeError”, 后面有文档网站了，再在旁边加个跳转链接——让用户无死角地知道自己哪里用出问题了
> > 2. 如果nan：图表NaN的部分断开，hover显示NaN，summary和gridview显示，显示为'NaN'
> 
> 我们将在v0.2.0解决此问题

v0.1.5先可以把类型匹配的GridView和Summary显示出来？

**Comment by SAKURA-CAT** [comment]
> > > 1. 如果log类型不匹配: summary和gridview显示，但是显示的是“TypeError”, 后面有文档网站了，再在旁边加个跳转链接——让用户无死角地知道自己哪里用出问题了
> 
> > > 2. 如果nan：图表NaN的部分断开，hover显示NaN，summary和gridview显示，显示为'NaN'
> 
> > 
> 
> > 我们将在v0.2.0解决此问题
> 
> 
> 
> v0.1.5先可以把类型匹配的GridView和Summary显示出来？
> 
> 完全空白的体验非常的灾难

不是很好改哦，因为这涉及表格和接口本身
但是v0.2.0会重写一次表格，到时候顺带着一起改了
