### ISSUE TITLE
[FEATURE] Hope to complete API documentation and API conversion guides.

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#233]
## 🤩 Features description [Please make everyone to understand it]

1. Please add a complete function API documentation in the tutorial, to facilitate quick searches for specific functionalities we need to use. It would also be helpful for quickly understanding the meaning of SwanLab functions used in other people's projects.
2.  Please add a comparison table between SwanLab functions and Wandb/TensorBoard functions? This would be very useful for quick reference when converting code.

## 👍 What problem does this feature solve

The current tutorials enable me to quickly start using SwanLab from scratch. However, when I try to convert an existing Tensorboard project to SwanLab, or take over someone else's project that includes SwanLab, I find there is a lack of reference documentation available.

## 👾 What does the proposed API look like

 New feature can refer to the API docs and API mapping tab in MindSpore documentation. [MindSpore API docs](https://www.mindspore.cn/docs/zh-CN/r2.2/note/api_mapping/pytorch_api_mapping.html) [MindSpore API mapping docs docs](https://www.mindspore.cn/docs/zh-CN/r2.2/note/api_mapping/pytorch_api_mapping.html). Just including the key API mappings would be very helpful for working with SwanLab. ; )

**Comment by SAKURA-CAT** [comment]
#153

**Comment by xiaolin199912** [comment]
❤️ The architecture and granularity of the API Docs are what we need to study.

**Comment by xiaolin199912** [comment]
Docs Page will release in v0.3.0
