### ISSUE TITLE
[FEATURE] class `swanlab.run`

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#235]
## 🤩 Features description [Please make everyone to understand it]

需要定义1个`swanlab.run`类，由`swanlab.init`实例化。
实际上`swanlab.run`一定程度上是替代了v0.1.5版本前的`swanlab.init`，新的`swanlab.init`是基于`swanlab.run`的一层封装。

支持以下用例：

1. config

```python
import swanlab

run = swanlab.init()
run.config.lr = 0.01
```

```python
import swanlab

run = swanlab.init()
config = run.config
config.lr = 0.01
```

运行实验看板时，config表格将出现`lr`

2. log

```python
import swanlab

run = swanlab.init()
run.log({'loss': loss})

...

**Comment by SAKURA-CAT** [comment]
现在就有类似效果，只是没有代码注释而已，用户可以选择`swanlab.log`或者`run.log`其中之一的方法，两者基本等价

**Comment by SAKURA-CAT** [comment]
在v0.1.5版本将完善`run.log`相关注释，以提高代码可读性

**Comment by xiaolin199912** [comment]
SwanConfig目前是只读状态，支持上述config用例需要增加读写交互性

**Comment by SAKURA-CAT** [comment]
fixed by #248
