### ISSUE TITLE
[FEATURE] better error message about SWANLAB_LOG_DIR must be an existing path

### ISSUE THREAD

**Issue by defineHong** [SwanHubX/SwanLab#239]
## 🤩 Features description [Please make everyone to understand it]

When I specify the 'logdir' for swanlab in my training code, swanlab does not correctly provide me with the command to view the logs in the training log, as shown in the following code and its corresponding output."

code:

```
 swanlab.init(
      experiment_name=str(cfg.log.exp_name),
      description="Honor inpaint model experiment",
      config=None,
      logdir=cfg.log.save_dir,
  )
```

output:

```
...
[2024-01-20 19:07:44,367][SwanLab][INFO] - Run data will be saved locally in 
/home/XXX/projects/HonorInpaint/experiments/baseline_2024-01-20_19-07-43
[SwanLab-INFO]:        Experiment_name: baseline_2024-01-20_19-07-43
[2024-01-20 19:07:44,367][SwanLab][INFO] - Experiment_name: baseline_2024-01-20_19-07-43
[SwanLab-INFO]:        Run `swanlab watch` to view SwanLab Experiment Dashboard
[2024-01-20 19:07:44,368][SwanLab][INFO] - Run `swanlab watch` to view SwanLab Experiment Dashboard
...
```

When I follow the output and use the `swanlab watch` command to view the logs, an error occurs, and the error message is as follows:

```
...
  File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/cli/main.py", line 64, in watch
    from ..server import app
  File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/server/__init__.py", line 14, in <module>
    init_env()
  File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 135, in init_env
    func(env)
  File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 52, in get_swanlog_dir
    raise ValueError('SWANLAB_LOG_DIR must be an existing path, now is "{path}"'.format(path=path))
ValueError: SWANLAB_LOG_DIR must be an existing path, now is "/home/XXX/projects/PROJECTNAME/swanlog"
```

I understand that this is caused by not correctly setting the log path, but I wish for a clearer error message to guide me in setting up the 'swanlab watch' command correctly when I forget to set the log path. Likes:

```
The log file was not found in the default path '/home/XXX/projects/PROJECTNAME/swanlog'. Please use the 'swanlab watch -d {LOG PATH}' command to specify the location of the log path."
```

**Comment by defineHong** [comment]
It seems there is an error in the tutorial. Using the '-d' option does not allow specifying the log path.

```
(inpaint) XXX@trainer1:~/projects/PROJECT$ swanlab watch -d ./experiemnts
Usage: swanlab watch [OPTIONS]
Try 'swanlab watch --help' for help.

Error: No such option: -d
```

**Comment by xiaolin199912** [comment]
> It seems there is an error in the tutorial. Using the '-d' option does not allow specifying the log path.
> 
> ```
> (inpaint) XXX@trainer1:~/projects/PROJECT$ swanlab watch -d ./experiemnts
> Usage: swanlab watch [OPTIONS]
> Try 'swanlab watch --help' for help.
> 
> Error: No such option: -d
> ```

Already Fix this

**Comment by xiaolin199912** [comment]
> ## 🤩 功能描述【请让大家明白】
> 当我在训练代码中为 swanlab 指定“logdir”时，swanlab 没有正确为我提供查看训练日志中的日志的命令，如以下代码及其相应输出所示。”
> 
> 代码：
> 
> ```
>  swanlab.init(
>       experiment_name=str(cfg.log.exp_name),
>       description="Honor inpaint model experiment",
>       config=None,
>       logdir=cfg.log.save_dir,
>   )
> ```
> 
> 输出：
> 
> ```
> ...
> [2024-01-20 19:07:44,367][SwanLab][INFO] - Run data will be saved locally in 
> /home/XXX/projects/HonorInpaint/experiments/baseline_2024-01-20_19-07-43
> [SwanLab-INFO]:        Experiment_name: baseline_2024-01-20_19-07-43
> [2024-01-20 19:07:44,367][SwanLab][INFO] - Experiment_name: baseline_2024-01-20_19-07-43
> [SwanLab-INFO]:        Run `swanlab watch` to view SwanLab Experiment Dashboard
> [2024-01-20 19:07:44,368][SwanLab][INFO] - Run `swanlab watch` to view SwanLab Experiment Dashboard
> ...
> ```
> 
> 当我按照输出结果使用`swanlab watch`命令查看日志时，出现错误，错误信息如下：
> 
> ```
> ...
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/cli/main.py", line 64, in watch
>     from ..server import app
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/server/__init__.py", line 14, in <module>
>     init_env()
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 135, in init_env
>     func(env)
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 52, in get_swanlog_dir
>     raise ValueError('SWANLAB_LOG_DIR must be an existing path, now is "{path}"'.format(path=path))
> ValueError: SWANLAB_LOG_DIR must be an existing path, now is "/home/XXX/projects/PROJECTNAME/swanlog"
> ```
> 
> 我知道这是由于未正确设置日志路径引起的，但我希望当我忘记设置日志路径时有更清晰的错误消息来指导我正确设置“swanlab watch”命令。喜欢：
> 
> ```
> The log file was not found in the default path '/home/XXX/projects/PROJECTNAME/swanlog'. Please use the 'swanlab watch -d {LOG PATH}' command to specify the location of the log path."
> ```

your advice is a better error message bro

**Comment by xiaolin199912** [comment]
> ## 🤩 Features description [Please make everyone to understand it]
> When I specify the 'logdir' for swanlab in my training code, swanlab does not correctly provide me with the command to view the logs in the training log, as shown in the following code and its corresponding output."
> 
> code:
> 
> ```
>  swanlab.init(
>       experiment_name=str(cfg.log.exp_name),
>       description="Honor inpaint model experiment",
>       config=None,
>       logdir=cfg.log.save_dir,
>   )
> ```
> 
> output:
> 
> ```
> ...
> [2024-01-20 19:07:44,367][SwanLab][INFO] - Run data will be saved locally in 
> /home/XXX/projects/HonorInpaint/experiments/baseline_2024-01-20_19-07-43
> [SwanLab-INFO]:        Experiment_name: baseline_2024-01-20_19-07-43
> [2024-01-20 19:07:44,367][SwanLab][INFO] - Experiment_name: baseline_2024-01-20_19-07-43
> [SwanLab-INFO]:        Run `swanlab watch` to view SwanLab Experiment Dashboard
> [2024-01-20 19:07:44,368][SwanLab][INFO] - Run `swanlab watch` to view SwanLab Experiment Dashboard
> ...
> ```
> 
> When I follow the output and use the `swanlab watch` command to view the logs, an error occurs, and the error message is as follows:
> 
> ```
> ...
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/cli/main.py", line 64, in watch
>     from ..server import app
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/server/__init__.py", line 14, in <module>
>     init_env()
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 135, in init_env
>     func(env)
>   File "/home/XXX/miniconda3/envs/inpaint/lib/python3.11/site-packages/swanlab/env.py", line 52, in get_swanlog_dir
>     raise ValueError('SWANLAB_LOG_DIR must be an existing path, now is "{path}"'.format(path=path))
> ValueError: SWANLAB_LOG_DIR must be an existing path, now is "/home/XXX/projects/PROJECTNAME/swanlog"
> ```
> 
> I understand that this is caused by not correctly setting the log path, but I wish for a clearer error message to guide me in setting up the 'swanlab watch' command correctly when I forget to set the log path. Likes:
> 
> ```
> The log file was not found in the default path '/home/XXX/projects/PROJECTNAME/swanlog'. Please use the 'swanlab watch -d {LOG PATH}' command to specify the location of the log path."
> ```

your advice is a better error message bro
