### ISSUE TITLE
Logfile Merge

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#292]
maybe can design a API or Python script, support two folder merge one.

**Comment by defineHong** [comment]
It would be very nice if we could merge the results of two experiments using the 'cp' command.

**Comment by defineHong** [comment]
> It would be very nice if we could merge the results of two experiments using the 'cp' command.

This feature was avaible before version 0.1.4

**Comment by SAKURA-CAT** [comment]
我觉得这没什么太大用处, 哈哈哈
