### ISSUE TITLE
[BUG] When the x-axis step reaches hundreds of thousands, the chart display seems to have problem

### ISSUE THREAD

**Issue by clairdelunejs** [SwanHubX/SwanLab#300]
## 🐛 Bug description 

When the x-axis reaches hundreds of thousands, the chart display seems to crash at some time
![img_v3_027k_11bfcdf0-2b7b-4539-8d0e-dc9cf6d8223g](https://github.com/SwanHubX/SwanLab/assets/118089335/95cc374a-85b5-4337-89c7-db54d7d8b60f)

- **SwanLab Version**:0.1.6beta1

- **Platform**:linux

**Comment by xiaolin199912** [comment]
problem discoverer @defineHong

**Comment by xiaolin199912** [comment]
same issue: #312
