### ISSUE TITLE
[BUG] the chart is not displayed correctly

### ISSUE THREAD

**Issue by clairdelunejs** [SwanHubX/SwanLab#301]
## 🐛 Bug description

When the number of steps setted reaches over 5 thousand or so , the chart is always not displayed correctly during program operation, often resulting in the following display.The chart may display in a correct way only after updating the page,lasting a short time before the same problem occurs again.
But the chart displays in a correct way after the program stops running anyway.
![KSNaPh0bgn](https://github.com/SwanHubX/SwanLab/assets/118089335/e7a6e241-1826-4a7a-9d9f-781e973ce4ba)
the test code is as follows:
```python
import math
import swanlab
import numpy as np

swanlab.init(
    config={"learning_rate": 0.01},
    )

for x in np.arange(0,20*np.pi, 0.0001):
    swanlab.log({"Sine Function": math.sin(x)})
```

- **SwanLab Version**:0.1.6

- **Platform**:Windows-10

**Comment by xiaolin199912** [comment]
Can you provide a piece of test code and a screen recording? This will help us better identify the problem.
