### ISSUE TITLE
[BUG] Zoom-in chart progress not synchronized with background

### ISSUE THREAD

**Issue by Nexisato** [SwanHubX/SwanLab#303]
![image](https://github.com/SwanHubX/SwanLab/assets/50736785/69bf4ef7-37d2-4add-bf44-e16235bbd79c)

## 🐛 Bug description [Please make everyone to understand it]
1. Press the **play button** in the background chart;
2. Zoom in the audio chart while the audio is playing;
3. The progress in the zoom-in chart reset and is not synchronized with which in the background.

https://github.com/SwanHubX/SwanLab/assets/50736785/a55e23bc-0502-4c76-a5e9-b7a714f24113

**Comment by SAKURA-CAT** [comment]
Zooming in on the chart is equivalent to re-rendering a new

**Comment by SAKURA-CAT** [comment]
At present, this method is more efficient. If synchronization is needed, many places need to be changed. Personally, I don't think it is necessary.
