### ISSUE TITLE
[QUESTION]  Console Buffer

### ISSUE THREAD

**Issue by Feudalman** [SwanHubX/SwanLab#304]
### 🤔 Question description [Please make everyone to understand it]

We have the `Consonler` class to controll the prints and logs, sending them to terminal and log file.
But in different process models, initialization parameter passing varies.

![image](https://github.com/SwanHubX/SwanLab/assets/74649535/39fd1088-a0c8-4956-9f87-aee415478054)

**1. In the main process**
Only allow one buffer:  `super().__init__(sys.stdout.buffer)`

**2. In Subprocess**
Two buffer required: `super().__init__(buffer1, buffer2)`

<hr>

To handle it, we can do this:

![img_v3_027l_0163468c-b1ad-4689-b700-3ce2935958dg](https://github.com/SwanHubX/SwanLab/assets/74649535/38b1331f-b359-445d-a4fd-590b34c25080)

**Comment by SAKURA-CAT** [comment]
目前的策略还是截断，因为终端日志收集并不是我们的主要工作，保持一个允许用户debug观看即可。
