### ISSUE TITLE
[QUESTION] Keep sorting same as user input

### ISSUE THREAD

**Issue by Feudalman** [SwanHubX/SwanLab#324]
### 🤔 Question description [Please make everyone to understand it]

Keep sorting same as user input.

![img_v3_027s_914449dd-a273-4c04-aeb2-704bab24202g](https://github.com/SwanHubX/SwanLab/assets/74649535/e4758007-2127-4a69-9e57-75b776320e85)

![img_v3_027s_39530c67-dad7-45c6-a6ed-6c2b98fb1f4g](https://github.com/SwanHubX/SwanLab/assets/74649535/971f0eea-8474-44b3-8c40-b2ae448422d8)

**Comment by SAKURA-CAT** [comment]
Now supported
