### ISSUE TITLE
SwanLab在Jupyter中训练结束会显示持续训练的状态

### ISSUE THREAD

**Issue by defineHong** [SwanHubX/SwanLab#36]
感谢[KashiwaByte](https://github.com/KashiwaByte)提的bug

![img_v3_0267_ad031bca-0a2f-4ce7-b6b6-30e4e929f8bg](https://github.com/SwanHubX/swanlab/assets/35194781/f382050d-3fac-44f1-9867-f99e40848c60)

在jupyter中单个cell中运行训练，cell结束执行后swanlab依然会显示在训练中的问题。
针对jupyter是否需要单独支持呢？
针对上述问题的解决方案可以参考：https://www.volcengine.com/theme/5839871-R-7-1

**Comment by defineHong** [comment]
相比于前端手动标记实验暂停，是否可以考虑增加函数来标记实验暂停，如通过显式调用swanlab.log.finish()来表示实验顺利完成？

**Comment by SAKURA-CAT** [comment]
> 相比于前端手动标记实验暂停，是否可以考虑增加函数来标记实验暂停，如通过显式调用swanlab.log.finish()来表示实验顺利完成？

可以，我们可以考虑两种方式兼容地使用
