### ISSUE TITLE
在Colab中初始化会报错

### ISSUE THREAD

**Issue by KashiwaByte** [SwanHubX/SwanLab#363]
## 🐛 Bug description [Please make everyone to understand it]

When initializing in Colab, Swanlab will be wrong

## 🧑‍💻 Step to reproduce

1. Go to Colab

2. Click Swanlab.init()

3. Something happened 

![image](https://github.com/SwanHubX/SwanLab/assets/106975133/6efc1947-e149-4567-80f3-6db39463ac3f)

- **SwanLab Version**:
swablab 0.2.0
- **Platform**:
Google Colab

**Comment by KashiwaByte** [comment]
Not only Colab，when using swanlab in local jupyter notebook，same problem also happened
![image](https://github.com/SwanHubX/SwanLab/assets/106975133/22a71f3f-83f9-40ef-8216-c3c0df708f17)

**Comment by xiaolin199912** [comment]
We will fix it in v0.2.2
