### ISSUE TITLE
[BUG] 如果前端正在运行，新增加的图表无法显示，页面也无法跳转

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#366]
## 🐛 Bug description [Please make everyone to understand it]

如果前端正在运行，并且有一部分图表在运行时被新增，则会造成一些错误
存在副作用就是，无法实现页面的跳转

## 🧑‍💻 Step to reproduce

1. 假设有个图表在10秒钟后被log

2. 在十秒钟之内进入前端界面，就能触发此bug

这样会带来副作用，页面也无法跳转

## 👾 Expected result

正常显示

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: 0.2.1

- **Platform**: macOS

**Comment by SAKURA-CAT** [comment]
我们计划在0.2.2修复此问题

**Comment by byzhrichard** [comment]
666
