### ISSUE TITLE
[BUG] 多实验图表中，当1次隐藏/显示多个实验时，刷新后会出现问题

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#368]
## 🐛 Bug description [Please make everyone to understand it]

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/8aee5859-2ab5-4548-9904-a0c101e1cc3a)

多实验图表中，当1次隐藏/显示多个实验时，点击刷新，会有1个实验回到操作前的状态

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.1dev

- **Platform**: Ubuntu

**Comment by xiaolin199912** [comment]
测试了一下，应该也跟切换后，点击刷新的速度有一定关系

**Comment by SAKURA-CAT** [comment]
没有问题，这里做了前端防抖，点击后0.5秒才会发请求
正常使用中有人在点击0.5秒内刷新页面的概率很低

**Comment by xiaolin199912** [comment]
> 没有问题，这里做了前端防抖，点击后0.5秒才会发请求 正常使用中有人在点击0.5秒内刷新页面的概率很低

我在正常使用会遇到——主要出现在点击2个以上的眼睛时

**Comment by SAKURA-CAT** [comment]
哦，那是bug，有空修复
