### ISSUE TITLE
[BUG] In Image Chart, clicking on the step bar when the image is not fully rendered will cause an error.

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#373]
## 🐛 Bug description [Please make everyone to understand it]

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/183d08f2-1f50-4253-bc2d-09f76902b23f)

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/e5b8a578-dc68-48ee-b560-abf65130ecba)

## 🧑‍💻 Step to reproduce

1. ImageChart is rendering a step, not yet completed

2. Click on another step

3. Error occurred, displayed as a blank page

## 👾 Expected result

正常显示

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.1dev

- **Platform**: Ubuntu

**Comment by SAKURA-CAT** [comment]
我无法复现此问题

**Comment by xiaolin199912** [comment]
> 我无法复现此问题

看起来似乎在其他PR中解决了

**Comment by SAKURA-CAT** [comment]
这个报错我已复现，但是并不是此issue描述的问题，也不影响正常使用
我会修复此问题
