### ISSUE TITLE
[FEATURE] Add compression ratio parameter for image saving

### ISSUE THREAD

**Issue by KashiwaByte** [SwanHubX/SwanLab#384]
## 🤩 Features description [Please make everyone to understand it]

add acompression ratioparameter for image saving , so that swanlab can store some useful image like model_graph clearly.
![image](https://github.com/SwanHubX/SwanLab/assets/106975133/970dc69f-fc71-4174-a0a1-1b6d313463a4)

## 👍 What problem does this feature solve
support image saving

## 👾 What does the proposed API look like
    swanlab.Image（image.png,cratio = 1.0）

**Comment by SAKURA-CAT** [comment]
We can use `swanlab.Image.cratio` for global settings

**Comment by xiaolin199912** [comment]
We add a `size` parameter in swanlab.Image, rule are as follows：
 
- The default size is None, which means no scaling
- If the size is an integer type such as 1024, it will be scaled if the side length exceeds 1024
- if the size is a list or tuple type, such as (512, 512), it will be scaled to that size; if it is (512, None) or (None, 512), then it will be proportionally scaled based on the side with a numerical value.
