### ISSUE TITLE
[BUG] Table Error

### ISSUE THREAD

**Issue by SAKURA-CAT** [SwanHubX/SwanLab#385]
## 🐛 Bug description [Please make everyone to understand it]

<img width="1728" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/79990647/7ef2b18e-accd-430f-81b1-d1fba933c940">

## 🧑‍💻 Step to reproduce

I don't know how to reproduce this bug.
It doesn't affect the use, but it's annoying to watch.

## 👾 Expected result

Fix this error and stop reporting it

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: 0.2.1

- **Platform**: macOS

**Comment by Feudalman** [comment]
怎么复现这个   偶尔几次触发过

**Comment by SAKURA-CAT** [comment]
> 怎么复现这个 偶尔几次触发过

我看一下

**Comment by SAKURA-CAT** [comment]
> 怎么复现这个 偶尔几次触发过

已复现此问题，首先，先进入存在此table组件的页面，比如首页，然后在不刷新页面的前提下进入其他页面，比如实验的页面
然后改变窗口大小，触发此报错，如下视频所示。

https://github.com/SwanHubX/SwanLab/assets/79990647/138de6f1-8abb-4eaa-b171-8bea0b69170a

这看起来应该是你组件卸载时没有一起卸载监听

**Comment by Feudalman** [comment]
了解  一会看看
