### ISSUE TITLE
[BUG] Delete Exp Bug

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#388]
## 🐛 Bug description [Please make everyone to understand it]

when delete a Exp, if the experiment has tags that other experiments do not have, deleting it will result in all charts of other experiments being empty.

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.1

- **Platform**: MacOS

**Comment by Feudalman** [comment]
![image](https://github.com/SwanHubX/SwanLab/assets/74649535/5df8f53c-d592-4eae-a4bf-d99d16c2d3fc)

在实例上调用自删除接口有问题，换用模型上的删除接口就好了，有点没搞懂问题到底出在那儿
