### ISSUE TITLE
[BUG] swanlab.init创建中停止运行，会触发Bug

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#412]
## 🐛 Bug description [Please make everyone to understand it]

<img width="1862" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/f3509be2-ac4f-4083-b2a7-e9a1b93b3465">

Write down the results you expect

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.3

**Comment by SAKURA-CAT** [comment]
主要是一些读取文件的步骤，需要考虑文件大小为0的问题
