### ISSUE TITLE
[FEATURE] Audio 图表 UI 优化

### ISSUE THREAD

**Issue by Feudalman** [SwanHubX/SwanLab#414]
![image](https://github.com/SwanHubX/SwanLab/assets/74649535/d1dacef3-7b31-48ff-84f5-cde15e5a201e)

高度降低一点，上下留白一点

**Comment by SAKURA-CAT** [comment]
这主要看正常的音频效果如何，你可以试试正常音频

**Comment by ZhikangNiu** [comment]
@Feudalman 我觉得你可以参考一下audio preview的插件的一些内容。https://marketplace.visualstudio.com/items?itemName=sukumo28.wav-preview

**Comment by SAKURA-CAT** [comment]
> @Feudalman 我觉得你可以参考一下audio preview的插件的一些内容。[marketplace.visualstudio.com/items?itemName=sukumo28.wav-preview](https://marketplace.visualstudio.com/items?itemName=sukumo28.wav-preview)

我们使用了一个第三方音频可视化库：https://github.com/katspaugh/wavesurfer.js，将在近期上线云端版本
