### ISSUE TITLE
[BUG] 多实验图表-只有一个Step时，Index位置变动，且无法拖动

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#455]
![img_v3_029o_d961ab56-032b-4070-89a5-4a9589cb5c3g](https://github.com/SwanHubX/SwanLab/assets/58305964/8c8160d6-3e0b-4dcc-b281-f0547c027003)

**Comment by SAKURA-CAT** [comment]
Index长度为1本身就不能拖动，不过确实算是显示的bug，当index为1时，将此拖动条隐藏
