### ISSUE TITLE
[BUG] 在多实验图表中，拖拽Audio类型图表的Index时，音频显示崩溃

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#463]
## 🐛 Bug description [Please make everyone to understand it]

拖拽Step正常，拖拽Index会崩溃

<img width="2250" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/b9e01b85-dd22-432b-9597-8244de7a6ee3">

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.4

- **Platform**: Ubuntu

**Comment by SAKURA-CAT** [comment]
https://github.com/SwanHubX/SwanLab-Dashboard/issues/18
