### ISSUE TITLE
[BUG] 上传日志对于swanlab开始和结束的某几行记录不到

### ISSUE THREAD

**Issue by Feudalman** [SwanHubX/SwanLab#488]
![1455a228-a21a-4181-97c4-809a14d11103](https://github.com/SwanHubX/SwanLab/assets/74649535/45592033-6069-4be0-8559-80706116df74)

![cd618dac-f2cd-452d-afec-9a98d00ad6b7](https://github.com/SwanHubX/SwanLab/assets/74649535/4cb1018d-2d4c-42e7-bac9-34656ba08467)

最后两行收不到，实验日志初始化也有几行收不到，大概是因为上传线程还未启动的问题

**Comment by SAKURA-CAT** [comment]
测试时发现swanlog的相关输出流函数无法一开始就输出，目前不太清楚是什么问题

**Comment by SAKURA-CAT** [comment]
> 测试时发现swanlog的相关输出流函数无法一开始就输出，目前不太清楚是什么问题

已解决

**Comment by SAKURA-CAT** [comment]
后面将考虑把所有与swanlog输出相关的都隐藏，因此此issue关闭
