### ISSUE TITLE
需要适配Jupyter Notebook的特性

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#493]
## 🤩 Features description [Please make everyone to understand it]

- [x] 支持swanlab.finish()后，可再次swanlab.init()
- [x] 事件循环（asyncio）适配Jupyter环境
- [ ] （不紧急）离线仪表盘-在执行`%swanlab -l [logdir]`时，支持异步启动一个watch服务，并收到URL，在jupyter端IFrame进去

**Comment by SAKURA-CAT** [comment]
在 #499 中使用多线程以解决jp中的协程适配问题
