### ISSUE TITLE
[ADVICE] 希望在创建存放日志的文件夹时自动生成.gitignore

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#505]
## 🤪 Features description [Please make everyone to understand it]

目前swanlab在日志文件夹时会生成多种类型后缀的文件，在未设置.gitignore时会产生大量的跟踪文件，新手经常容易失误将整个日志文件push上去。建议在创建文件夹时同时默认生成忽略当前文件夹内文件的.gitignore。
<img width="715" alt="Screenshot 2024-04-27 at 04 44 10" src="https://github.com/SwanHubX/SwanLab/assets/35194781/46a48cbf-658b-4f2f-8692-fe697b54e7fb">

## 👍 What problem does this feature solve

可以在指定swanlab.init中或者在其他地方增加create_gitignore参数，默认为True。当创建新的日志存放文件夹时自动在新建的文件夹下添加.gitignore文件，文件中使用*将包括.gitignore在内的所有文件忽略跟踪，以此使得git工具忽略所有的日志文件（通常日志并不需要进行版本跟踪）
<img width="451" alt="Screenshot 2024-04-27 at 04 46 39" src="https://github.com/SwanHubX/SwanLab/assets/35194781/5597cba6-5313-4ad9-948d-636bb1b18815">

**Comment by ShaohonChen** [comment]
如果我希望添加一个这个功能，我是否能在如下位置添加呢？

@SAKURA-CAT 

<img width="835" alt="Screenshot 2024-04-27 at 11 21 14" src="https://github.com/SwanHubX/SwanLab/assets/35194781/68919218-b11d-4778-9ab5-239fa816ddca">

**Comment by xiaolin199912** [comment]
其他的日志跟踪工具似乎都没加gitignore，需要挖掘commit日志文件的优缺点
