### ISSUE TITLE
[BUG] 日志搜索大写字母搜不了，小写可以

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#523]
## 🐛 Bug description [Please make everyone to understand it]

<img width="1169" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/d75ba083-d41a-46e3-9188-dc3c9602bbab">

<img width="772" alt="image" src="https://github.com/SwanHubX/SwanLab/assets/58305964/d346ad1f-5986-4c84-90bc-6c7edede4265">

**Comment by Feudalman** [comment]
日志搜索已屏蔽大小写检查
