### ISSUE TITLE
[ADVICE] 可以下载swanlab绘制的数据折线图

### ISSUE THREAD

**Issue by bwcd-123** [SwanHubX/SwanLab#534]
希望能在控制面板可以直接把绘制的折线图保存到本地

**Comment by Zeyi-Lin** [comment]
谢谢你的建议，我们会关注并尽快安排这个功能。
你希望保存本地的格式是什么，我猜比如jpg、png、csv？

**Comment by bwcd-123** [comment]
我希望是png，这样写报告就不用再做一遍图了

**Comment by Zeyi-Lin** [comment]
> 我希望是png，这样写报告就不用再做一遍图了

🎉Get！我们会尽快安排此功能，也欢迎你提出更多建议

**Comment by Zeyi-Lin** [comment]
> 我希望是png，这样写报告就不用再做一遍图了

png下载已经上线咯，在这里下载：

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/cacc5c8d-0b08-4255-b89a-5586ecc75b03)
