### ISSUE TITLE
[BUG] 日志云端/本地无法保存

### ISSUE THREAD

**Issue by OliverZhai1515** [SwanHubX/SwanLab#536]
## 🐛 log输出无法保存

Describe the main elements of the bug

## 🧑‍💻 Step to reproduce

执行代码如下：
![Snipaste_2024-05-07_18-04-17](https://github.com/SwanHubX/SwanLab/assets/136923194/eb1745fa-20db-4f37-a75f-2213cdd669ac)

## 👾 Expected result

![Snipaste_2024-05-07_18-09-39](https://github.com/SwanHubX/SwanLab/assets/136923194/5082736f-0472-4deb-90dc-05c6838ae5be)

## 🚑 Any additional

swanlog/run-xxxx/console中的log输出正常
![Snipaste_2024-05-07_18-07-39](https://github.com/SwanHubX/SwanLab/assets/136923194/bdf83d5f-65d2-4749-b5d1-79aa7d5de050)

但是本地查看和云端查看都显示`no log`.

- **SwanLab Version**: 0.3.1

- **Platform**: Ubuntu20.04

**Comment by SAKURA-CAT** [comment]
> 但是本地查看和云端查看都显示

你好，我们测试后发现云端应该是可以显示的。不过本地确实有些问题，马上修复。

**Comment by ShaohonChen** [comment]
测试代码：

main.py:

```python
import swanlab
import hydra

import omegaconf
from omegaconf import DictConfig, OmegaConf
import random

import logging


@hydra.main(version_base=None, config_path="conf", config_name="config")
def my_app(cfg: DictConfig) -> None:
    run = swanlab.init(
        project=cfg.project_name,
        experiment_name="test-swanlab",
        description="test",
        config=cfg,
    )
    swanlab.config = omegaconf.OmegaConf.to_container(
        cfg, resolve=True, throw_on_missing=True
    )
    # loss = random.random()
    # swanlab.log({"loss": loss})
    print(OmegaConf.to_yaml(cfg))
    logging.info(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()
```

conf/configs.yaml:

```yaml
project_name: 'debug'
lr: 0.01
model: 'noname'
```

**Comment by SAKURA-CAT** [comment]
> > 但是本地查看和云端查看都显示
> 
> 你好，我们测试后发现云端应该是可以显示的。不过本地确实有些问题，马上修复。

本地后端有一些问题，第一行如果为空就会有这个bug

**Comment by SAKURA-CAT** [comment]
fixed by https://github.com/SwanHubX/SwanLab/commit/fb746967a0321516bc58e566bc9900e23299bd4f

**Comment by OliverZhai1515** [comment]
感谢，重新安装swanlab后正常了。
