### ISSUE TITLE
[REQUEST] swanlab.log增加参数section

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#540]
## 🤩 Features description [Please make everyone to understand it]

```python
swanlab.log(pin=True, hide=True)
```

在首次创建该Chart时，放到pin或hide分组

**Comment by SAKURA-CAT** [comment]
`swanlab.log(display='pin')`会好一些，这两个参数本质上应该是一类东西。

**Comment by Zeyi-Lin** [comment]
用swanlab.log(section='pin')，section可以决定分组，优先级大于key的前缀
