### ISSUE TITLE
[BUG] 上传媒体文件的409 error

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#565]
在一些情况下，log媒体文件会出现问题，报409 api错误，前端的显示为持续加载中。

![img_v3_02b3_296b2a7a-6dcb-412f-89d2-dfecd8ddb0bg](https://github.com/SwanHubX/SwanLab/assets/58305964/9a7a4bf4-8df0-4e98-aaee-40ef4ec74814)

**Comment by SAKURA-CAT** [comment]
哪些情况下？

**Comment by Zeyi-Lin** [comment]
在使用fastai集成时，在train中途Ctrl+C时，会稳定出现409报错；
判断是多线程问题。
