### ISSUE TITLE
[ADVICE] 增加针对Hydra分层配置文件云端显示的展开折叠功能

### ISSUE THREAD

**Issue by nxZhai** [SwanHubX/SwanLab#626]
## 🤪 Features description [Please make everyone to understand it]
集成Hydra的分层配置文件时, 只有单变量会显示美观, 内部的字典变量还是按原始格式显示. 希望在云端能增加针对字典的展开折叠功能.
## 👍 What problem does this feature solve

![image](https://github.com/SwanHubX/SwanLab/assets/136923194/60f9e463-8190-4b1f-9ef2-5eca15fe860f)

## 🚑 Any additional [like screenshots]
以下是我参考文档写的入口脚本. 看了下issues没有查到这个问题, 如果是我忽视了解决方案请提醒我~感谢
```python
@hydra.main(version_base=None, config_path="configs", config_name="config")
def main(cfg: DictConfig):
    # swanlab init
    run = swanlab.init(
                        project=cfg.swanlab.project,
                        experiment_name=cfg.swanlab.experiment_name,
                        config=omegaconf.OmegaConf.to_container(
                                cfg, resolve=True, throw_on_missing=True))
```

**Comment by Zeyi-Lin** [comment]
谢谢建议，我们会关注这个feature

**Comment by Zeyi-Lin** [comment]
我们会在7～8月之间与“表格视图的优化”、“实验分组”等这些涉及到更好的表格的特性一起，实现这个功能

**Comment by SAKURA-CAT** [comment]
done!
