### ISSUE TITLE
[QUESTION] pip install 无法安装 python3.9 swanlab最新版

### ISSUE THREAD

**Issue by zeminroot** [SwanHubX/SwanLab#645]
ERROR: HTTP error 404 while getting http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/540/b4cc0d2c072dd/swanlab-0.3.9-py3-none-any.whl#sha256=540b4cc0d2c072dda1e6098042017c40c87605af6309d4d5c699b4fc27451941 (from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/+simple/swanlab/) (requires-python:>=3.8)
ERROR: Could not install requirement swanlab==0.3.9 from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/540/b4cc0d2c072dd/swanlab-0.3.9-py3-none-any.whl#sha256=540b4cc0d2c072dda1e6098042017c40c87605af6309d4d5c699b4fc27451941 because of HTTP error 404 Client Error: Not Found for url: http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/540/b4cc0d2c072dd/swanlab-0.3.9-py3-none-any.whl for URL http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/540/b4cc0d2c072dd/swanlab-0.3.9-py3-none-any.whl#sha256=540b4cc0d2c072dda1e6098042017c40c87605af6309d4d5c699b4fc27451941 (from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/+simple/swanlab/) (requires-python:>=3.8)

**Comment by SAKURA-CAT** [comment]
最新版应该是安装3.13噢，不是3.9，3.9我记得有大bug被我们删除了

**Comment by SAKURA-CAT** [comment]
使用`pip install swanlab==3.13`试试呢

**Comment by SAKURA-CAT** [comment]
还有一种可能是您python版本过低，因为根据报错来看其中有一个`requires-python:>=3.8`

**Comment by ShaohonChen** [comment]
您这边如果用k8s的话，有可能是用的系统中的python而非您期望指定的python？

**Comment by ShaohonChen** [comment]
如果有类似问题可以联系重启这个issue
