### ISSUE TITLE
[BUG] win11下swanlab task list显示抖动问题

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#664]
## 🐛 Bug description [Please make everyone to understand it]

`swanlab task list`命令在win11的命令提示符或者powershell中会出现显示抖动问题。等到右下方 Log Messages 刷新到最大时会消失。目前推测是因为 Log Messages 的框的刷新方式会导致抖动。

https://github.com/user-attachments/assets/53f350b8-09f0-4414-877a-6d8b599d7235

**Comment by SAKURA-CAT** [comment]
估计是emoji表情导致的

**Comment by ShaohonChen** [comment]
我感觉不是emoji，是log message不停渲染造成的

**Comment by SAKURA-CAT** [comment]
可以，下个版本将所有emoji去掉

**Comment by ShaohonChen** [comment]
真的是因为emoji嘛 @SAKURA-CAT

**Comment by SAKURA-CAT** [comment]
> 真的是因为emoji嘛 @SAKURA-CAT 
> 
> 

总之应该是右边那个东西的缘故，新版本改成别的了
