### ISSUE TITLE
🤩 [FEATURE] 日期显示格式调整

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#67]
## 🤩 Features description [Please make everyone to understand it]

![AUHFt0TwVy](https://github.com/SwanHubX/SwanLab/assets/58305964/37ed8c8b-e7dc-4d3c-a71b-966a1fd3a7ea)
将时间在个位数时的显示格式从“X”改为“0X”，如“8”->"08"

**Comment by Feudalman** [comment]
![img_v3_026d_04898e8b-4254-4cee-a58a-1e8a75a1ad6g](https://github.com/SwanHubX/SwanLab/assets/74649535/841b7d69-486b-4360-8b99-822a46e00c9a)

问题出在这个地方，需要处理一下 second
