### ISSUE TITLE
[REQUEST] 环境-增加Nvidia驱动信息

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#672]
![img_v3_02dl_d1e43376-62d1-4981-b422-ed9a8ec17edg](https://github.com/user-attachments/assets/7e25925f-2590-4429-aa82-357a0de0b500)

**Comment by ZhikangNiu** [comment]
> ![img_v3_02dl_d1e43376-62d1-4981-b422-ed9a8ec17edg](https://private-user-images.githubusercontent.com/58305964/356865665-7e25925f-2590-4429-aa82-357a0de0b500.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjY1ODEsIm5iZiI6MTcyMzYyNjI4MSwicGF0aCI6Ii81ODMwNTk2NC8zNTY4NjU2NjUtN2UyNTkyNWYtMjU5MC00NDI5LWFhODItMzU3YTBkZTBiNTAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNTEwMjdhYmFiNzRlM2Q2YzRhNGMwOTBhYjgwMzhlYmI3Y2Q2ZmU5NTY2YTVlNjJiYWM3OTFiMDRlOTE3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cs0mv7I9qEsXzw90HwR3sk2wCaLvU3LFvHnaISaVaRQ)

感觉加上当前的 cuda compiler driver是哪一个也可以。nvcc -V。因为可能有的人会存在多个cuda，但是cuda path load错了

**Comment by SAKURA-CAT** [comment]
此信息在 https://github.com/SwanHubX/SwanLab/pull/668 合并后前端已经上线了测试环境，等待下一次部署后上线正式环境。
![img_v3_02do_608a3850-cbc5-4ba7-9a89-8e8991126b0g](https://github.com/user-attachments/assets/df2097ab-44db-4758-9a1d-a65802a82580)

**Comment by SAKURA-CAT** [comment]
已上线

**Comment by Zeyi-Lin** [comment]
> > ![img_v3_02dl_d1e43376-62d1-4981-b422-ed9a8ec17edg](https://private-user-images.githubusercontent.com/58305964/356865665-7e25925f-2590-4429-aa82-357a0de0b500.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjY1ODEsIm5iZiI6MTcyMzYyNjI4MSwicGF0aCI6Ii81ODMwNTk2NC8zNTY4NjU2NjUtN2UyNTkyNWYtMjU5MC00NDI5LWFhODItMzU3YTBkZTBiNTAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNTEwMjdhYmFiNzRlM2Q2YzRhNGMwOTBhYjgwMzhlYmI3Y2Q2ZmU5NTY2YTVlNjJiYWM3OTFiMDRlOTE3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cs0mv7I9qEsXzw90HwR3sk2wCaLvU3LFvHnaISaVaRQ)
> 
> 感觉加上当前的 cuda compiler driver是哪一个也可以。nvcc -V。因为可能有的人会存在多个cuda，但是cuda path load错了

不错的想法，我再提一个Issue记录一下。
