### ISSUE TITLE
[ADVICE] Support log export

### ISSUE THREAD

**Issue by Puiching-Memory** [SwanHubX/SwanLab#675]
## 🤪 Features description [Please make everyone to understand it]

The plan will support exports in the following formats:

- [ ] csv
- [ ] txt
- [ ] json
- [ ] db(sqlite3)
- [ ] html (single)
- [ ] pdf

After exporting, we can provide compression in the following formats:

- [ ] zip
- [ ] rar
- [ ] 7zip
- [ ] tar
- [ ] gzip

Of course, we also need the ability to load the exported logs back:

- [ ] decode
- [ ] unzip

## 👍 What problem does this feature solve

https://github.com/SwanHubX/SwanLab/issues/360
https://github.com/SwanHubX/SwanLab/issues/166

## 👾 What does the proposed API look like

```python
swanlab.export(log_path,format,using_zip)
swanlab.import(log_file,save_path)
```
> cil

```
swanlab export --log_path {} --format {} --using_zip {}
swanlab import --log_file {} --save_path {}
```

**Comment by SAKURA-CAT** [comment]
我比较好奇，这个功能的主要用途在于什么地方呢？我没有太理解
