### ISSUE TITLE
[BUG] win10、win11下登陆400报错问题

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#688]
## bug报告

在win10、win11下使用windows自带的命令提示符运行`swanlab login`命令会出现400错误

同时出现显示乱码的问题

<img width="839" alt="Screenshot 2024-08-30 at 13 23 44" src="https://github.com/user-attachments/assets/3bbc657e-2705-43e6-8efb-a663e1162792">

并且powershell下也会出现同样的问题：

<img width="721" alt="Screenshot 2024-08-30 at 13 27 55" src="https://github.com/user-attachments/assets/deb30512-91f0-429d-ba4f-65d641069e6e">

目测降低版本也无法避免这个bug（降到0.3.1都不行，不过我看0.3.1的网址本身也有问题），下图为0.3.16的截图

<img width="823" alt="Screenshot 2024-08-30 at 13 32 29" src="https://github.com/user-attachments/assets/c6896657-b1ca-40ca-be13-660d6832eee1">

目测故意输错一个key也会产生400报错

## 暂时解决方案

不使用命令行登陆，转为使用python命令登陆可以解决

```python
import swanlab
swanlab.login(api_key=你的apikey)
```

**Comment by swpfY** [comment]
使用新版本命令提示符似乎没有这个问题

<img width="867" alt="img_v3_02e8_6e08a9cc-6ea9-4249-b960-b4deca6e01ag" src="https://github.com/user-attachments/assets/6e988f09-ccca-4250-9790-ee44e9abb0af">
