### ISSUE TITLE
[QUESTION] swanlab.log不起作用了

### ISSUE THREAD

**Issue by Giserlei123** [SwanHubX/SwanLab#693]
上午还能正常显示log中记录下的指标，下午突然发现显示不了了，代码没有做过修改，
![image](https://github.com/user-attachments/assets/421981bf-e5a0-4bf3-9e9c-afaf81b5a26e)
![image](https://github.com/user-attachments/assets/f35137b2-457d-48d3-ae68-285b067581df)

**Comment by Zeyi-Lin** [comment]
已修复了该问题
