### ISSUE TITLE
把置顶的图表解除置顶后不会回到原先的位置

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#700]
<img width="1310" alt="Screenshot 2024-09-08 at 16 17 52" src="https://github.com/user-attachments/assets/ccba264d-c90d-4c6f-922d-2140a45132c6">

图表如果原先有分组，置顶后解除置顶分组信息会被覆盖掉。

建议单独保存一下原先的分组信息，或者对标题名称再进行一次解析

**Comment by SAKURA-CAT** [comment]
云端是这样的，未来方案是改成"section"的pin/hide逻辑+拖拽选择图表在section的位置

**Comment by SAKURA-CAT** [comment]
暂时没有更新的计划，未来会优化。
