### ISSUE TITLE
[QUESTION] transformers集成中可能存在参数未正常记录的问题

### ISSUE THREAD

**Issue by ShaohonChen** [SwanHubX/SwanLab#702]
![image](https://github.com/user-attachments/assets/21a2b4b2-9f2f-4728-8638-7cae79b0de97)

需要检查下是否能够在model的config中使用to_dict()函数来获得模型参数

**Comment by ShaohonChen** [comment]
似乎也会引起潜在bug

**Comment by ShaohonChen** [comment]
![image](https://github.com/user-attachments/assets/2ea878df-32cd-4cad-ba48-632f157b332a)

**Comment by ShaohonChen** [comment]
@SAKURA-CAT 能否帮我看看这个可能是什么引起的呢

**Comment by SAKURA-CAT** [comment]
transformer的IntervalStrategy枚举类继承了str，绕过了swanlab的config对象检查：

<img width="591" alt="image" src="https://github.com/user-attachments/assets/19205d15-79de-4e78-95bf-99e4bb66cf74">

此时直接将原对象返回，这是不可以的
