### ISSUE TITLE
请问下，离线看板怎么切换成中文版的呢？

### ISSUE THREAD

**Issue by yangy996** [SwanHubX/SwanLab#703]

**Comment by SAKURA-CAT** [comment]
暂时没有这个选项～

**Comment by yangy996** [comment]
> 暂时没有这个选项～

好吧，已经从源码里改成中文了

**Comment by SAKURA-CAT** [comment]
> > 暂时没有这个选项～
> 
> 好吧，已经从源码里改成中文了

需求已收到，我们尽量早些把此功能上线～

**Comment by Feudalman** [comment]
已在 [SwanLab-Dashboard](https://github.com/SwanHubX/SwanLab-Dashboard/pull/60) 完成，待下版本上线！感谢反馈！
