### ISSUE TITLE
[BUG] 云端日志界面显示的日志不能显示完整行，日志文件下载下来也不是完整行

### ISSUE THREAD

**Issue by ARSblithe212** [SwanHubX/SwanLab#729]
## 🐛 Bug description [Please make everyone to understand it]

Describe the main elements of the bug

## 🧑‍💻 Step to reproduce

1. Go to '....'

2. Click '....'

3. Something happened '....'
![Uploading image.png…
![Uploading 日志bug.png…]()
]()

## 👾 Expected result

Write down the results you expect

## 🚑 Any additional [like screenshots]

- **SwanLab Version**:

- **Platform**:

**Comment by ARSblithe212** [comment]
![Uploading 日志bug.png…]()

**Comment by SAKURA-CAT** [comment]
您好，您上传的图像有点问题打不开，能重新上传一张嘛？ 
<img width="419" alt="image" src="https://github.com/user-attachments/assets/2a99d7a0-71c5-4005-be14-2c7062c65790">
