### ISSUE TITLE
[QUESTION] 对每次训练run进行命名

### ISSUE THREAD

**Issue by JinKe-11** [SwanHubX/SwanLab#743]
现在在swanlab.init中仍旧没有对训练进行命名的接口吗？

**Comment by Zeyi-Lin** [comment]
不知道你指的是不是这个：
```python
swanlab.init(experiment_name="Run的名字")
```

**Comment by JinKe-11** [comment]
> 不知道你指的是不是这个：
> 
> ```python
> swanlab.init(experiment_name="Run的名字")
> ```

感谢解疑，会去详细看一下文件

**Comment by JinKe-11** [comment]
> 不知道你指的是不是这个：
> 
> ```python
> swanlab.init(experiment_name="Run的名字")
> ```

感谢解疑，会去详细看一下文件
