### ISSUE TITLE
[BUG] Is there any problem when running on “root“ ？

### ISSUE THREAD

**Issue by GuoPingPan** [SwanHubX/SwanLab#81]
When I am running the ·swanlab watch· on a remote machine, and found the below bug.
It there the problem caused by running on "root" authority?

Waiting to fix it! 😀

![1703391248985](https://github.com/SwanHubX/SwanLab/assets/69315544/4ded76c4-13d1-455a-8456-aa134ad7cf67)

**Comment by GuoPingPan** [comment]
What‘s more, that is my system version below.
![1703391459290](https://github.com/SwanHubX/SwanLab/assets/69315544/fc0e79b8-adc2-4c4a-8071-a992ec23f2ea)

**Comment by SAKURA-CAT** [comment]
Thanks for the feedback! We'll try to troubleshoot...

**Comment by xiaolin199912** [comment]
@SAKURA-CAT Has the issue been resolved in v0.1.3?

**Comment by SAKURA-CAT** [comment]
> @SAKURA-CAT Has the issue been resolved in v0.1.3?

the milestone is v0.2.0, at present, there are still some problems to be solved.
