### ISSUE TITLE
🐛 [BUG] requirements-swan.txt is empty file

### ISSUE THREAD

**Issue by NoFish-528** [SwanHubX/SwanLab#82]
If unnecessary, I think we can delete it. (it makes people feel confused
![image](https://github.com/SwanHubX/SwanLab/assets/73390819/8939e77d-727d-4056-9e33-ddb3c6944823)

**Comment by Feudalman** [comment]
I think we may use this in the future.
This is a part of release.

**Comment by SAKURA-CAT** [comment]
In the future, requirements-swan.txt will be an additional dependency for pip installation, mainly to adapt to the public cloud version.
People can install additional dependencies on the public cloud through the following commands:

```
pip install swanlab[oauth]
```

Besides, This is configured in pyproject.toml in the project. Although this seems useless at the moment, it is to prepare for the future.

**Comment by NoFish-528** [comment]
great, thx. It's puzzled for me.

**Comment by NoFish-528** [comment]
I'll close this issue. If I have question, I will re-open this issue in the future : )
