### ISSUE TITLE
🐛 [BUG] When the experiment Finish, the status of `OverView/Experiment List` remains unchanged.

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#95]
## 🐛 Bug description [Please make everyone to understand it]

When a experiment is completed, the status of the experiment in the `Experiment List` in `Project OverView` does not change until the Browser is refreshed, and then it will be normal.

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/7f96e952-061e-44bd-80ac-1e6877145254)

## 👾 Expected result

Maybe refresh automatically when entering the Oview page?

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.1

- **Platform**: macOS-14.1.2-arm64-arm-64bit

**Comment by SAKURA-CAT** [comment]
fixed by #94
