### ISSUE TITLE
🤩 [FEATURE] More useful experiment suffix name

### ISSUE THREAD

**Issue by NoFish-528** [SwanHubX/SwanLab#96]
## 🤩 Features description [Please make everyone to understand it]

When we run exps with same setting, the swanlab will log every exp with number suffix name. For example, exp,exp-2,exp-3 ,exp-4 and exp-5. 

If we have a more useful suffix name, it'll be better. We can use current time as suffix name.

![img_v3_026h_ff90f49b-2048-47a3-b294-02b852190a3g](https://github.com/SwanHubX/SwanLab/assets/73390819/889718da-c617-47bf-a1c7-a6d8df740904)
 
you can study from: https://hydra.cc/docs/configure_hydra/workdir/

![image](https://github.com/SwanHubX/SwanLab/assets/73390819/e9067663-d253-4c05-a1c9-0faf9bf7033a)

**Comment by xiaolin199912** [comment]
用以下规则：
1. 如果未填写`experiment_name`，则默认名为`exp`，最终的实验名为：`exp-2024-01-02_14-55-36`
2. 如果填写了`experiment_name`，最终的实验名为f`{experiment_name}-2024-01-02_14-55-36`
3. 如果重复，则加`-1`
4. 默认加上时间戳

增强：
1. `swanlab.init`有一个参数，可以设置加后缀的规则（如时间戳格式、None为取消加时间戳后缀等）
